const englishVoices = [
    { label: "English (US) - Jenny", value: "en-US-JennyNeural" },
    { label: "English (US) - Guy", value: "en-US-GuyNeural" },
    { label: "English (UK) - Libby", value: "en-GB-LibbyNeural" },
    { label: "English (UK) - Ryan", value: "en-GB-RyanNeural" },
    { label: "English (Australia) - Natasha", value: "en-AU-NatashaNeural" },
    { label: "English (Canada) - Clara", value: "en-CA-ClaraNeural" },
  
    // Extended voices
    { label: "English (Australia) - William", value: "en-AU-WilliamNeural" },
    { label: "English (Canada) - Liam", value: "en-CA-LiamNeural" },
    { label: "English (UK) - Maisie", value: "en-GB-MaisieNeural" },
    { label: "English (UK) - Sonia", value: "en-GB-SoniaNeural" },
    { label: "English (UK) - Thomas", value: "en-GB-ThomasNeural" },
    { label: "English (Hong Kong) - Sam", value: "en-HK-SamNeural" },
    { label: "English (Hong Kong) - Yan", value: "en-HK-YanNeural" },
    { label: "English (Ireland) - Connor", value: "en-IE-ConnorNeural" },
    { label: "English (Ireland) - Emily", value: "en-IE-EmilyNeural" },
    {
      label: "English (India) - Neerja (Expressive)",
      value: "en-IN-NeerjaExpressiveNeural",
    },
    { label: "English (India) - Neerja", value: "en-IN-NeerjaNeural" },
    { label: "English (India) - Prabhat", value: "en-IN-PrabhatNeural" },
    { label: "English (Kenya) - Asilia", value: "en-KE-AsiliaNeural" },
    { label: "English (Kenya) - Chilemba", value: "en-KE-ChilembaNeural" },
    { label: "English (Nigeria) - Abeo", value: "en-NG-AbeoNeural" },
    { label: "English (Nigeria) - Ezinne", value: "en-NG-EzinneNeural" },
    {
      label: "English (New Zealand) - Mitchell",
      value: "en-NZ-MitchellNeural",
    },
    { label: "English (New Zealand) - Molly", value: "en-NZ-MollyNeural" },
    { label: "English (Philippines) - James", value: "en-PH-JamesNeural" },
    { label: "English (Philippines) - Rosa", value: "en-PH-RosaNeural" },
    { label: "English (Singapore) - Luna", value: "en-SG-LunaNeural" },
    { label: "English (Singapore) - Wayne", value: "en-SG-WayneNeural" },
    { label: "English (Tanzania) - Elimu", value: "en-TZ-ElimuNeural" },
    { label: "English (Tanzania) - Imani", value: "en-TZ-ImaniNeural" },
    { label: "English (US) - Ana", value: "en-US-AnaNeural" },
    {
      label: "English (US) - Andrew (Multilingual)",
      value: "en-US-AndrewMultilingualNeural",
    },
    { label: "English (US) - Andrew", value: "en-US-AndrewNeural" },
    { label: "English (US) - Aria", value: "en-US-AriaNeural" },
    {
      label: "English (US) - Ava (Multilingual)",
      value: "en-US-AvaMultilingualNeural",
    },
    { label: "English (US) - Ava", value: "en-US-AvaNeural" },
    {
      label: "English (US) - Brian (Multilingual)",
      value: "en-US-BrianMultilingualNeural",
    },
    { label: "English (US) - Brian", value: "en-US-BrianNeural" },
    { label: "English (US) - Christopher", value: "en-US-ChristopherNeural" },
    {
      label: "English (US) - Emma (Multilingual)",
      value: "en-US-EmmaMultilingualNeural",
    },
    { label: "English (US) - Emma", value: "en-US-EmmaNeural" },
    { label: "English (US) - Eric", value: "en-US-EricNeural" },
    { label: "English (US) - Michelle", value: "en-US-MichelleNeural" },
    { label: "English (US) - Roger", value: "en-US-RogerNeural" },
    { label: "English (US) - Steffan", value: "en-US-SteffanNeural" },
    { label: "English (South Africa) - Leah", value: "en-ZA-LeahNeural" },
    { label: "English (South Africa) - Luke", value: "en-ZA-LukeNeural" },
  
    // Chinese voices
    { label: "Chinese (Mainland) - Xiaoxiao", value: "zh-CN-XiaoxiaoNeural" },
    { label: "Chinese (Mainland) - Xiaoyi", value: "zh-CN-XiaoyiNeural" },
    { label: "Chinese (Mainland) - Yunjian", value: "zh-CN-YunjianNeural" },
    { label: "Chinese (Mainland) - Yunxi", value: "zh-CN-YunxiNeural" },
    { label: "Chinese (Mainland) - Yunxia", value: "zh-CN-YunxiaNeural" },
    { label: "Chinese (Mainland) - Yunyang", value: "zh-CN-YunyangNeural" },
    {
      label: "Chinese (Liaoning) - Xiaobei",
      value: "zh-CN-liaoning-XiaobeiNeural",
    },
    {
      label: "Chinese (Shaanxi) - Xiaoni",
      value: "zh-CN-shaanxi-XiaoniNeural",
    },
  ];

export default englishVoices;